# -*- coding: utf-8 -*-
"""happiness_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBAUMJufWB2DxrqhXQOXuKf_yiJbaTOz
"""

pip install streamlit

import streamlit as st 
import joblib 
import numpy as np

from PIL import Image

def prediction(GDP_per_capita,Social_support, Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption):  
    prediction = classifier.predict( [[GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption]])

reload_model = joblib.load('happiness_model')

def main():       
    # front end elements of the web page 
    html_temp = """ 
    <div style ="background-color:yellow;padding:13px"> 
    <h1 style ="color:black;text-align:center;">Streamlit happiness score Prediction ML App</h1> 
    </div> 
    """
      
    # display the front end aspect
    st.markdown(html_temp, unsafe_allow_html = True) 
      
    # following lines create boxes in which user can enter data required to make prediction 
    GDP_per_capita= st.text_input('GDP_per_capita')
    Social_support = st.text_input('Social_support') 
    Healthy_life_expectancy= st.text_input("Healthy_life_expectancy") 
    Freedom_to_make_life_choices= st.text_input('Freedom_to_make_life_choices')
    Generosity = st.text_input('Generosity') 
    Perceptions_of_corruption= st.text_input("Perceptions_of_corruption") 
    result =""





if st.button("Predict"): 
        result = prediction(GDP_per_capita,Social_support, Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption) 
        st.success('happiness score {}'.format(result))
        print(Score)

















